Fix tools/ci/tox script when 'python' command is not available
Change-Id: I73f5b45de60f47a489a8140ab63baa899599e34e

diff --git a/tools/ci/activate b/tools/ci/activate
--- a/tools/ci/activate
+++ b/tools/ci/activate
@@ -20,7 +20,8 @@ function get_realpath {
             local script=$("${python}" "${script}" "${script}")
             echo "${python}" "${script}"
         else
-            which realpath
+            echo "Python command not found!" 1>&2
+            exit 1
         fi
     )
 }
